### ISSUE TITLE
Password is not being sourced from .pause

### ISSUE THREAD

**Issue by mvgrimes** [perlancar/perl-App-pause#1]
When running with a `~/.pause` file but no `pause.conf` file, I get the following error:

    ERROR 400: Missing required argument: password

The `~/.pause` file contents are:

    user mgrimes 
    password SECRET

which is a little different than the `pause.conf` file format.

**Comment by perlancar** [comment]
Thanks for the report. Fixed in App-pause 0.60.

**Comment by perlancar** [comment]
Ref: https://github.com/perlancar/perl-WWW-PAUSE-Simple/commit/8b4622d1366eb9f687eceb31818900c621ee12ef
